### ISSUE TITLE
聚合镜像站当中的pypi与rust均无法使用

### ISSUE THREAD

**Issue by lilith-rong** [mzzsfy/Dockerfile#2]
cloudflare的workers的js脚本
custom-common-image.js
做出来的聚合镜像站，其中有一些并不能真正的使用，网页访问时，会直接反馈Error 1016，并且返回的内容显示域名为archive.ubuntu.comubuntu后面的/消失不见了，似乎是worker会自动删除单“/”？（不确定，是别的地方看到的）

**Comment by lilith-rong** [comment]
> cloudflare的workers的js脚本 custom-common-image.js 做出来的聚合镜像站，其中有一些并不能真正的使用，网页访问时，会直接反馈Error 1016，并且返回的内容显示域名为archive.ubuntu.comubuntu后面的/消失不见了，似乎是worker会自动删除单“/”？（不确定，是别的地方看到的）

我现在的解决方案是在108行加上了 "+ "\/" +"这段内容，如下所示
return await fetch(mirror + "\/" + path1.replace(path, replace)+url.search, {

或者在“路径:[镜像地址,替换路径]”的位置，每个替换路径不为空的内容，均在开头新增“/”

**Comment by mzzsfy** [comment]
有解决问题吗?如果已经解决问题,建议主动关闭

**Comment by lilith-rong** [comment]
其实依旧会出现问题，我也不知道为什么，看过那个替换代码了，似乎没有问题，但是不知道为什么，就是会继续出现二级路径和域名混在一起的问题

**Comment by mzzsfy** [comment]
现在应该好了,应该是空路径导致了替换'/xxx'为 'xxx'

**Comment by lilith-rong** [comment]
坏了，越修越坏了（x
现在是空路径的全都出问题的样子了

**Comment by mzzsfy** [comment]
加了日志,测试是没问题了

**Comment by mzzsfy** [comment]
![Clip_2024-07-10_16-55-51](https://github.com/mzzsfy/Dockerfile/assets/43053461/1bbbc815-65e6-4116-9fa9-b8f6d8ef303d)

**Comment by lilith-rong** [comment]
感谢大佬的修复，辛苦了
