### ISSUE TITLE
one-api里调用如何选择音色呢？默认就只有一个tts-1的模型

### ISSUE THREAD

**Issue by ddup001** [mzzsfy/Dockerfile#4]
首先感谢大佬。
我的问题如题：one-api里调用如何选择音色呢？默认就只有一个tts-1的模型

**Comment by mzzsfy** [comment]
写微软音色名称

**Comment by hanetyb** [comment]
请问我oneapi 接 tts怎么测试显示404 也无法正常调用，直接调用tts，不通过oneoneapi正常。请问应该怎么设置

![Image](https://github.com/user-attachments/assets/419ad427-28a8-4754-902f-3339c80ffdb9)

**Comment by mzzsfy** [comment]
> 请问我oneapi 接 tts怎么测试显示404 也无法正常调用，直接调用tts，不通过oneoneapi正常。请问应该怎么设置
> 
> ![Image](https://github.com/user-attachments/assets/419ad427-28a8-4754-902f-3339c80ffdb9)

没用过,请检查是否为兼容性问题

**Comment by hanetyb** [comment]
谢谢。我去问oneapi 看看有没有解决方案。不懂是否支持. 

另外这个有支持GPU版本吗

**Comment by mzzsfy** [comment]
> 谢谢。我去问oneapi 看看有没有解决方案。不懂是否支持.
> 
> 另外这个有支持GPU版本吗

调用微软api,跟本地算力无关
